# Generated by Django 5.2.5 on 2025-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mentor_status_user_portfolio_url_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mentor_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10, null=True),
        ),
    ]
