# Generated by Django 5.2.5 on 2025-08-09 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('mentors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='mentor_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mentors.mentoravailability'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingrequest',
            unique_together={('mentor_availability',)},
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='requested_time',
        ),
    ]
