version: '3.9'

services:
  db:
    image: postgres:14
    container_name: skillsphere_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillsphere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: skillsphere_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillsphere.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
